#ifndef _ESP32S3_N16R8_CUSTOM_CONFIG_H_
#define _ESP32S3_N16R8_CUSTOM_CONFIG_H_

#include <sdkconfig.h>
#include <driver/gpio.h>
#include <esp_adc/adc_oneshot.h>

#if defined(CONFIG_CUSTOM_AUDIO_CODEC_ES8311) || defined(CONFIG_CUSTOM_AUDIO_CODEC_ES8388) || \
    defined(CONFIG_CUSTOM_AUDIO_CODEC_ES8374) || defined(CONFIG_CUSTOM_AUDIO_CODEC_ES8389) || \
    defined(CONFIG_CUSTOM_AUDIO_CODEC_BOX) || defined(CONFIG_CUSTOM_AUDIO_I2S_DUPLEX) || \
    defined(CONFIG_CUSTOM_AUDIO_SPK_CODEC_ES8311) || defined(CONFIG_CUSTOM_AUDIO_SPK_CODEC_ES8388) || \
    defined(CONFIG_CUSTOM_AUDIO_SPK_CODEC_ES8374) || defined(CONFIG_CUSTOM_AUDIO_SPK_CODEC_ES8389) || \
    defined(CONFIG_CUSTOM_AUDIO_SPK_CODEC_BOX)
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#else
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#endif

// 1. Màn hình (Display)
#ifdef CONFIG_CUSTOM_DISPLAY_WIDTH
#define DISPLAY_WIDTH CONFIG_CUSTOM_DISPLAY_WIDTH
#else
#define DISPLAY_WIDTH 240
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_HEIGHT
#define DISPLAY_HEIGHT CONFIG_CUSTOM_DISPLAY_HEIGHT
#else
#define DISPLAY_HEIGHT 320
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_OFFSET_X
#define DISPLAY_OFFSET_X CONFIG_CUSTOM_DISPLAY_OFFSET_X
#else
#define DISPLAY_OFFSET_X 0
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_OFFSET_Y
#define DISPLAY_OFFSET_Y CONFIG_CUSTOM_DISPLAY_OFFSET_Y
#else
#define DISPLAY_OFFSET_Y 0
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_MOSI
#define DISPLAY_MOSI_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_MOSI)
#else
#define DISPLAY_MOSI_PIN GPIO_NUM_47
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_CLK
#define DISPLAY_CLK_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_CLK)
#else
#define DISPLAY_CLK_PIN GPIO_NUM_21
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_CS
#define DISPLAY_CS_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_CS)
#else
#define DISPLAY_CS_PIN GPIO_NUM_41
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_DC
#define DISPLAY_DC_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_DC)
#else
#define DISPLAY_DC_PIN GPIO_NUM_40
#endif

#if defined(CONFIG_CUSTOM_DISPLAY_USE_RST) && defined(CONFIG_CUSTOM_DISPLAY_PIN_RST)
#define DISPLAY_RST_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_RST)
#elif !defined(CONFIG_CUSTOM_DISPLAY_USE_RST) && defined(CONFIG_CUSTOM_DISPLAY_PIN_RST) && (CONFIG_CUSTOM_DISPLAY_PIN_RST >= 0)
#define DISPLAY_RST_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_RST)
#elif !defined(CONFIG_CUSTOM_DISPLAY_USE_RST) && !defined(CONFIG_CUSTOM_DISPLAY_PIN_RST)
#define DISPLAY_RST_PIN GPIO_NUM_42
#else
#define DISPLAY_RST_PIN GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_DISPLAY_USE_BLK) && defined(CONFIG_CUSTOM_DISPLAY_PIN_BLK)
#define DISPLAY_BACKLIGHT_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_BLK)
#elif !defined(CONFIG_CUSTOM_DISPLAY_USE_BLK) && defined(CONFIG_CUSTOM_DISPLAY_PIN_BLK) && (CONFIG_CUSTOM_DISPLAY_PIN_BLK >= 0)
#define DISPLAY_BACKLIGHT_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_BLK)
#elif !defined(CONFIG_CUSTOM_DISPLAY_USE_BLK) && !defined(CONFIG_CUSTOM_DISPLAY_PIN_BLK)
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_38
#else
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_I2C_SDA
#define DISPLAY_I2C_SDA_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_I2C_SDA)
#else
#define DISPLAY_I2C_SDA_PIN GPIO_NUM_8
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_PIN_I2C_SCL
#define DISPLAY_I2C_SCL_PIN ((gpio_num_t)CONFIG_CUSTOM_DISPLAY_PIN_I2C_SCL)
#else
#define DISPLAY_I2C_SCL_PIN GPIO_NUM_9
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_SWAP_XY
#define DISPLAY_SWAP_XY true
#else
#define DISPLAY_SWAP_XY false
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_MIRROR_X
#define DISPLAY_MIRROR_X true
#else
#define DISPLAY_MIRROR_X false
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_MIRROR_Y
#define DISPLAY_MIRROR_Y true
#else
#define DISPLAY_MIRROR_Y false
#endif

#ifdef CONFIG_CUSTOM_DISPLAY_INVERT_COLOR
#define DISPLAY_INVERT_COLOR true
#else
#define DISPLAY_INVERT_COLOR false
#endif

// 2. Màn hình Cảm ứng (Touch Screen)
#ifdef CONFIG_CUSTOM_TOUCH_PIN_SDA
#define TOUCH_I2C_SDA_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_SDA)
#else
#define TOUCH_I2C_SDA_PIN GPIO_NUM_8
#endif

#ifdef CONFIG_CUSTOM_TOUCH_PIN_SCL
#define TOUCH_I2C_SCL_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_SCL)
#else
#define TOUCH_I2C_SCL_PIN GPIO_NUM_9
#endif

#if defined(CONFIG_CUSTOM_TOUCH_USE_INT) && defined(CONFIG_CUSTOM_TOUCH_PIN_INT)
#define TOUCH_INT_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_INT)
#elif !defined(CONFIG_CUSTOM_TOUCH_USE_INT) && defined(CONFIG_CUSTOM_TOUCH_PIN_INT) && (CONFIG_CUSTOM_TOUCH_PIN_INT >= 0)
#define TOUCH_INT_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_INT)
#elif !defined(CONFIG_CUSTOM_TOUCH_USE_INT) && !defined(CONFIG_CUSTOM_TOUCH_PIN_INT)
#define TOUCH_INT_PIN GPIO_NUM_3
#else
#define TOUCH_INT_PIN GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_TOUCH_USE_RST) && defined(CONFIG_CUSTOM_TOUCH_PIN_RST)
#define TOUCH_RST_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_RST)
#elif !defined(CONFIG_CUSTOM_TOUCH_USE_RST) && defined(CONFIG_CUSTOM_TOUCH_PIN_RST) && (CONFIG_CUSTOM_TOUCH_PIN_RST >= 0)
#define TOUCH_RST_PIN ((gpio_num_t)CONFIG_CUSTOM_TOUCH_PIN_RST)
#elif !defined(CONFIG_CUSTOM_TOUCH_USE_RST) && !defined(CONFIG_CUSTOM_TOUCH_PIN_RST)
#define TOUCH_RST_PIN GPIO_NUM_2
#else
#define TOUCH_RST_PIN GPIO_NUM_NC
#endif

// 3. Âm thanh (Audio I2S & Codec)
#ifdef CONFIG_CUSTOM_AUDIO_MIC_GPIO_WS
#define AUDIO_I2S_MIC_GPIO_WS ((gpio_num_t)CONFIG_CUSTOM_AUDIO_MIC_GPIO_WS)
#else
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#endif

#ifdef CONFIG_CUSTOM_AUDIO_MIC_GPIO_SCK
#define AUDIO_I2S_MIC_GPIO_SCK ((gpio_num_t)CONFIG_CUSTOM_AUDIO_MIC_GPIO_SCK)
#else
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#endif

#ifdef CONFIG_CUSTOM_AUDIO_MIC_GPIO_DIN
#define AUDIO_I2S_MIC_GPIO_DIN ((gpio_num_t)CONFIG_CUSTOM_AUDIO_MIC_GPIO_DIN)
#else
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#endif

#ifdef CONFIG_CUSTOM_AUDIO_SPK_GPIO_DOUT
#define AUDIO_I2S_SPK_GPIO_DOUT ((gpio_num_t)CONFIG_CUSTOM_AUDIO_SPK_GPIO_DOUT)
#else
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#endif

#ifdef CONFIG_CUSTOM_AUDIO_SPK_GPIO_BCLK
#define AUDIO_I2S_SPK_GPIO_BCLK ((gpio_num_t)CONFIG_CUSTOM_AUDIO_SPK_GPIO_BCLK)
#else
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#endif

#ifdef CONFIG_CUSTOM_AUDIO_SPK_GPIO_LRCK
#define AUDIO_I2S_SPK_GPIO_LRCK ((gpio_num_t)CONFIG_CUSTOM_AUDIO_SPK_GPIO_LRCK)
#else
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16
#endif

#ifdef CONFIG_CUSTOM_AUDIO_CODEC_I2C_SDA
#define AUDIO_CODEC_I2C_SDA_PIN ((gpio_num_t)CONFIG_CUSTOM_AUDIO_CODEC_I2C_SDA)
#else
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_8
#endif

#ifdef CONFIG_CUSTOM_AUDIO_CODEC_I2C_SCL
#define AUDIO_CODEC_I2C_SCL_PIN ((gpio_num_t)CONFIG_CUSTOM_AUDIO_CODEC_I2C_SCL)
#else
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_9
#endif

// 4. Camera Pins
#ifdef CONFIG_CUSTOM_CAM_PIN_XCLK
#define CAM_PIN_XCLK ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_XCLK)
#else
#define CAM_PIN_XCLK GPIO_NUM_10
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_PCLK
#define CAM_PIN_PCLK ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_PCLK)
#else
#define CAM_PIN_PCLK GPIO_NUM_12
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_VSYNC
#define CAM_PIN_VSYNC ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_VSYNC)
#else
#define CAM_PIN_VSYNC GPIO_NUM_13
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_HREF
#define CAM_PIN_HREF ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_HREF)
#else
#define CAM_PIN_HREF GPIO_NUM_14
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_SIOD
#define CAM_PIN_SIOD ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_SIOD)
#else
#define CAM_PIN_SIOD GPIO_NUM_8
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_SIOC
#define CAM_PIN_SIOC ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_SIOC)
#else
#define CAM_PIN_SIOC GPIO_NUM_9
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D0
#define CAM_PIN_D0 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D0)
#else
#define CAM_PIN_D0 GPIO_NUM_11
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D1
#define CAM_PIN_D1 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D1)
#else
#define CAM_PIN_D1 GPIO_NUM_2
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D2
#define CAM_PIN_D2 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D2)
#else
#define CAM_PIN_D2 GPIO_NUM_46
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D3
#define CAM_PIN_D3 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D3)
#else
#define CAM_PIN_D3 GPIO_NUM_21
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D4
#define CAM_PIN_D4 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D4)
#else
#define CAM_PIN_D4 GPIO_NUM_47
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D5
#define CAM_PIN_D5 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D5)
#else
#define CAM_PIN_D5 GPIO_NUM_48
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D6
#define CAM_PIN_D6 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D6)
#else
#define CAM_PIN_D6 GPIO_NUM_45
#endif

#ifdef CONFIG_CUSTOM_CAM_PIN_D7
#define CAM_PIN_D7 ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_D7)
#else
#define CAM_PIN_D7 GPIO_NUM_40
#endif

#if defined(CONFIG_CUSTOM_CAM_USE_RESET) && defined(CONFIG_CUSTOM_CAM_PIN_RESET)
#define CAM_PIN_RESET ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_RESET)
#elif !defined(CONFIG_CUSTOM_CAM_USE_RESET) && defined(CONFIG_CUSTOM_CAM_PIN_RESET) && (CONFIG_CUSTOM_CAM_PIN_RESET >= 0)
#define CAM_PIN_RESET ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_RESET)
#else
#define CAM_PIN_RESET GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_CAM_USE_PWDN) && defined(CONFIG_CUSTOM_CAM_PIN_PWDN)
#define CAM_PIN_PWDN ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_PWDN)
#elif !defined(CONFIG_CUSTOM_CAM_USE_PWDN) && defined(CONFIG_CUSTOM_CAM_PIN_PWDN) && (CONFIG_CUSTOM_CAM_PIN_PWDN >= 0)
#define CAM_PIN_PWDN ((gpio_num_t)CONFIG_CUSTOM_CAM_PIN_PWDN)
#else
#define CAM_PIN_PWDN GPIO_NUM_NC
#endif

// 5. UART
#ifdef CONFIG_CUSTOM_UART_PORT_2
#define CUSTOM_UART_PORT UART_NUM_2
#else
#define CUSTOM_UART_PORT UART_NUM_1
#endif

#ifdef CONFIG_CUSTOM_UART_PIN_TX
#define CUSTOM_UART_TX_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_TX)
#else
#define CUSTOM_UART_TX_PIN GPIO_NUM_17
#endif

#ifdef CONFIG_CUSTOM_UART_PIN_RX
#define CUSTOM_UART_RX_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_RX)
#else
#define CUSTOM_UART_RX_PIN GPIO_NUM_18
#endif

#if defined(CONFIG_CUSTOM_UART_USE_FLOW_CONTROL) && defined(CONFIG_CUSTOM_UART_PIN_RTS)
#define CUSTOM_UART_RTS_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_RTS)
#elif !defined(CONFIG_CUSTOM_UART_USE_FLOW_CONTROL) && defined(CONFIG_CUSTOM_UART_PIN_RTS) && (CONFIG_CUSTOM_UART_PIN_RTS >= 0)
#define CUSTOM_UART_RTS_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_RTS)
#else
#define CUSTOM_UART_RTS_PIN GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_UART_USE_FLOW_CONTROL) && defined(CONFIG_CUSTOM_UART_PIN_CTS)
#define CUSTOM_UART_CTS_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_CTS)
#elif !defined(CONFIG_CUSTOM_UART_USE_FLOW_CONTROL) && defined(CONFIG_CUSTOM_UART_PIN_CTS) && (CONFIG_CUSTOM_UART_PIN_CTS >= 0)
#define CUSTOM_UART_CTS_PIN ((gpio_num_t)CONFIG_CUSTOM_UART_PIN_CTS)
#else
#define CUSTOM_UART_CTS_PIN GPIO_NUM_NC
#endif

#ifdef CONFIG_CUSTOM_UART_BAUD_RATE
#define CUSTOM_UART_BAUDRATE CONFIG_CUSTOM_UART_BAUD_RATE
#else
#define CUSTOM_UART_BAUDRATE 115200
#endif

// 6. Cảm biến & Đo Pin
#ifdef CONFIG_CUSTOM_BATTERY_ADC_CHANNEL
#define BATTERY_ADC_CHANNEL ((adc_channel_t)CONFIG_CUSTOM_BATTERY_ADC_CHANNEL)
#else
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_0
#endif

#ifdef CONFIG_CUSTOM_BATTERY_DIVIDER_R1
#define BATTERY_DIVIDER_R1 CONFIG_CUSTOM_BATTERY_DIVIDER_R1
#else
#define BATTERY_DIVIDER_R1 100
#endif

#ifdef CONFIG_CUSTOM_BATTERY_DIVIDER_R2
#define BATTERY_DIVIDER_R2 CONFIG_CUSTOM_BATTERY_DIVIDER_R2
#else
#define BATTERY_DIVIDER_R2 100
#endif

// 7. LED & Phím bấm
#ifdef CONFIG_CUSTOM_LED_GPIO
#define BUILTIN_LED_GPIO ((gpio_num_t)CONFIG_CUSTOM_LED_GPIO)
#else
#define BUILTIN_LED_GPIO GPIO_NUM_48
#endif

#ifdef CONFIG_CUSTOM_LED_COUNT
#define BUILTIN_LED_COUNT CONFIG_CUSTOM_LED_COUNT
#else
#define BUILTIN_LED_COUNT 1
#endif

#if defined(CONFIG_CUSTOM_ENABLE_BUTTON_BOOT) && defined(CONFIG_CUSTOM_BUTTON_BOOT_GPIO)
#define BOOT_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_BOOT_GPIO)
#elif defined(CONFIG_CUSTOM_ENABLE_BUTTON_BOOT)
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#elif defined(CONFIG_CUSTOM_BUTTON_BOOT_GPIO) && (CONFIG_CUSTOM_BUTTON_BOOT_GPIO >= 0)
#define BOOT_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_BOOT_GPIO)
#elif !defined(CONFIG_CUSTOM_ENABLE_BUTTON_BOOT) && !defined(CONFIG_CUSTOM_BUTTON_BOOT_GPIO)
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#else
#define BOOT_BUTTON_GPIO GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_ENABLE_BUTTON_TOUCH) && defined(CONFIG_CUSTOM_BUTTON_TOUCH_GPIO)
#define TOUCH_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_TOUCH_GPIO)
#elif defined(CONFIG_CUSTOM_ENABLE_BUTTON_TOUCH)
#define TOUCH_BUTTON_GPIO GPIO_NUM_1
#elif !defined(CONFIG_CUSTOM_ENABLE_BUTTON_TOUCH) && defined(CONFIG_CUSTOM_BUTTON_TOUCH_GPIO) && (CONFIG_CUSTOM_BUTTON_TOUCH_GPIO >= 0)
#define TOUCH_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_TOUCH_GPIO)
#else
#define TOUCH_BUTTON_GPIO GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME) && defined(CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO)
#define VOLUME_UP_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO)
#elif defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME)
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_2
#elif !defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME) && defined(CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO) && (CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO >= 0)
#define VOLUME_UP_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO)
#else
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#endif

#if defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME) && defined(CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO)
#define VOLUME_DOWN_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO)
#elif defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME)
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_3
#elif !defined(CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME) && defined(CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO) && (CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO >= 0)
#define VOLUME_DOWN_BUTTON_GPIO ((gpio_num_t)CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO)
#else
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#endif

// 8. MCP Server Lamp / Relay
#ifdef CONFIG_CUSTOM_MCP_LAMP_GPIO
#define LAMP_GPIO ((gpio_num_t)CONFIG_CUSTOM_MCP_LAMP_GPIO)
#elif defined(CONFIG_CUSTOM_PERIPH_RELAY_GPIO)
#define LAMP_GPIO ((gpio_num_t)CONFIG_CUSTOM_PERIPH_RELAY_GPIO)
#else
#define LAMP_GPIO GPIO_NUM_13
#endif

// 9. Cảm biến phổ biến (Popular Sensors)
#ifdef CONFIG_CUSTOM_SENSOR_DHT_GPIO
#define SENSOR_DHT_GPIO ((gpio_num_t)CONFIG_CUSTOM_SENSOR_DHT_GPIO)
#else
#define SENSOR_DHT_GPIO GPIO_NUM_NC
#endif

#ifdef CONFIG_CUSTOM_SENSOR_HCSR04_TRIG_GPIO
#define SENSOR_HCSR04_TRIG_GPIO ((gpio_num_t)CONFIG_CUSTOM_SENSOR_HCSR04_TRIG_GPIO)
#else
#define SENSOR_HCSR04_TRIG_GPIO GPIO_NUM_NC
#endif

#ifdef CONFIG_CUSTOM_SENSOR_HCSR04_ECHO_GPIO
#define SENSOR_HCSR04_ECHO_GPIO ((gpio_num_t)CONFIG_CUSTOM_SENSOR_HCSR04_ECHO_GPIO)
#else
#define SENSOR_HCSR04_ECHO_GPIO GPIO_NUM_NC
#endif

#ifdef CONFIG_CUSTOM_SENSOR_PIR_GPIO
#define SENSOR_PIR_GPIO ((gpio_num_t)CONFIG_CUSTOM_SENSOR_PIR_GPIO)
#else
#define SENSOR_PIR_GPIO GPIO_NUM_NC
#endif

#endif // _ESP32S3_N16R8_CUSTOM_CONFIG_H_
