export const DEFAULT_CONFIG = {
  system: {
    cpu_freq:        "240",
    flash_size:      "16MB",
    flash_mode:      "QIO",
    flash_freq:      "80M",
    spiram:          true,
    spiram_mode:     "OCT",
    spiram_speed:    "80M",
    partition_table: "partitions/16m.csv",
  },
  assistant: {
    language: "LANGUAGE_VI_VN",
    ota_url: "https://api.tenclass.net/xiaozhi/ota/",
    wakeup_word: "WAKEUP_WORD_XIAOZHI",
    wake_word_method: "WAKE_WORD_AFE",
    enable_listening_wake_word: false,
    audio_processor: "CUSTOM_AUDIO_AEC",
  },
  general: {
    language:          "LANGUAGE_VI_VN",
    ota_url:           "https://api.tenclass.net/xiaozhi/ota/",
    flash_assets:      "FLASH_DEFAULT_ASSETS",
    custom_assets_file:"https://github.com/78/xiaozhi-esp32/releases/download/v0.9/assets.bin",
    display_style:     "USE_DEFAULT_MESSAGE_STYLE",
    multiline_chat:    false,
  },
  display: {
    enable:           false,
    type:             "CUSTOM_DISPLAY_ST7789",
    width:            240,  height: 320,
    pin_mosi: -1, pin_clk: -1, pin_cs: -1, pin_dc: -1,
    use_rst:  true,  pin_rst: -1,
    use_blk:  true,  pin_blk: -1,
    pin_i2c_sda: -1, pin_i2c_scl: -1,
    offset_x: 0,  offset_y: 0,
    mirror_x: false, mirror_y: false, swap_xy: false, invert_color: false,
    uart_secondary:  false,
    uart_port:       1,
    uart_tx:        -1,   uart_rx: -1,
    uart_baud:       115200,
    uart_proto:      "CUSTOM_DISPLAY_UART_PROTO_NEXTION",
    amoled_chip:     "CUSTOM_DISPLAY_AMOLED_SH8601",
    qspi_cs:-1, qspi_clk:-1, qspi_d0:-1, qspi_d1:-1,
    qspi_d2:-1, qspi_d3:-1, qspi_rst:-1,
    epaper_busy: -1,
    rgb_pclk:-1, rgb_de:-1, rgb_vsync:-1, rgb_hsync:-1,
    rgb_d0:-1,  rgb_d1:-1,  rgb_d2:-1,  rgb_d3:-1,
    rgb_d4:-1,  rgb_d5:-1,  rgb_d6:-1,  rgb_d7:-1,
    rgb_d8:-1,  rgb_d9:-1,  rgb_d10:-1, rgb_d11:-1,
    rgb_d12:-1, rgb_d13:-1, rgb_d14:-1, rgb_d15:-1,
  },
  touch: {
    enable:   false,
    type:     "CUSTOM_TOUCH_CST816S",
    pin_sda: -1, pin_scl: -1, pin_int: -1, pin_rst: -1,
  },
  speaker: {
    enable:        false,
    type:          "CUSTOM_AUDIO_DAC_MAX98357A",
    pin_dout:     -1, pin_bclk: -1, pin_lrck: -1,
    codec_sda:    -1, codec_scl: -1,
  },
  mic: {
    enable:        false,
    type:          "CUSTOM_AUDIO_MIC_INMP441",
    pin_din:      -1, pin_sck: -1, pin_ws: -1,
    codec_sda:    -1, codec_scl: -1,
  },
  audio: {
    i2s_mode: "CUSTOM_AUDIO_I2S_SIMPLEX",
  },
  wakeword: {
    type:                  "USE_AFE_WAKE_WORD",
    custom_word:           "xiao tu dou",
    custom_display:        "小土豆",
    threshold:             20,
    device_aec:            true,
    server_aec:            false,
    send_data:             true,
    detection_in_listening:false,
  },
  network: {
    wifi_method: "USE_HOTSPOT_WIFI_PROVISIONING",
    cellular_enable: false,
    cellular_module: "CUSTOM_4G_A7670",
    cellular_tx: -1,
    cellular_rx: -1,
    cellular_baud: 115200,
    cellular_pwrkey: -1,
    cellular_rst: -1,
    cellular_apn: "v-internet",
    uart_ext_enable: false,
    uart_ext_port: "CUSTOM_UART_PORT_1",
    uart_ext_tx: -1,
    uart_ext_rx: -1,
    uart_ext_baud: 115200,
    mcp_enable: false
  },
  wifi: {
    method: "USE_HOTSPOT_WIFI_PROVISIONING",
  },
  buttons: {
    boot_enable:   true, boot_gpio:     0, boot_extra_gpios: "",
    touch_enable:  false, touch_gpio:    -1,
    vol_enable:    false, vol_up_gpio:   -1, vol_down_gpio: -1,
    slider_enable: false,
    slider_pad1:  -1, slider_pad2: -1, slider_pad3: -1,
    rotary_enable: false,
    rotary_a:     -1, rotary_b: -1, rotary_key: -1,
    user_custom_sensors: false,
  },
  camera: {
    enable:    false,
    sensor:    "CUSTOM_CAMERA_OV2640",
    pin_xclk: -1, pin_pclk: -1, pin_vsync: -1, pin_href: -1,
    pin_siod: -1, pin_sioc: -1,
    use_reset: false, pin_reset: -1,
    use_pwdn:  false, pin_pwdn:  -1,
    pin_d0:   -1, pin_d1: -1, pin_d2: -1, pin_d3: -1,
    pin_d4:   -1, pin_d5: -1, pin_d6: -1, pin_d7: -1,
    hmirror:  false, vflip: false,
  },
  led: {
    enable:  true,
    type:    "CUSTOM_LED_WS2812",
    gpio:   48,
    count:   1,
    rainbow: true,
  },
  mcp: {
    enable:   false,
    lamp:     true, lamp_gpio: -1, lamp_extra_gpios: "",
    sensor:   true,
    actuator: true,
  },
  uart: {
    enable:       false,
    port:         "CUSTOM_UART_PORT_1",
    pin_tx:      -1, pin_rx: -1,
    baudrate:     115200,
    flow_ctrl:    false,
    pin_rts:     -1, pin_cts: -1,
  },
  actuators: {
    servo_enable:  false, servo_gpio:  -1,
    buzzer_enable: false, buzzer_gpio: -1, buzzer_extra_pins: "",
    haptic_enable: false, haptic_gpio: -1,
  },
  motor: {
    relay_enable:   false, relay_gpio:  -1,
    dc_enable:      false,
    dc_driver:      "CUSTOM_MOTOR_DRIVER_TB6612",
    pwma: -1, dira: -1, pwmb: -1, dirb: -1,
  },
  sensors: {
    dht_enable:   false, dht_gpio:      -1, dht_extra_gpios: "",
    temp_enable:  false, aht20:         true,
    temp_sda:    -1,     temp_scl:      -1, temp_extra_gpios: "",
    bmp280:       false, bmp280_sda:   -1, bmp280_scl: -1, bmp280_extra_gpios: "",
    bh1750:       false, bh1750_sda:   -1, bh1750_scl: -1, bh1750_extra_gpios: "",
    ldr:          false, ldr_ch:        1, ldr_extra_chs: "",
    gas_co2:      false, gas_scd4x:     true,
    gas_sda:     -1,     gas_scl:      -1, gas_extra_gpios: "",
    gas_mq:       false, gas_mq_gpio:  -1,
    hcsr04:       false, hcsr04_trig:  -1, hcsr04_echo: -1,
    pir:          false, pir_gpio:     -1,
    vibration:    false, vibration_gpio:-1,
    flame:        false, flame_gpio:   -1,
  },
  build: {
    log_level: "INFO",
    baud_rate: "115200",
    touch_suppress: true,
    md5_partition: true,
  },
  power: {
    battery_enable: false,
    battery_adc:    true,  battery_ch: 0,
    battery_r1:     100,   battery_r2: 100,
    ina2xx:         false, ina219: true,
    ina_sda:       -1,     ina_scl: -1,
    tp4056:         false, tp4056_gpio: -1,
  },
};
if (typeof window !== 'undefined') {
  window.configState = JSON.parse(JSON.stringify(DEFAULT_CONFIG));
  window.conflictErrors = [];
  window.isServerMode = false;
  window.serverProjectInfo = null;
  window.apiFetch = function(endpoint, options = {}) {
    let url = endpoint;
    if (window.location.protocol === 'file:') {
      url = 'http://localhost:8080' + endpoint;
    }
    return fetch(url, options);
  };
}
