import { ESP32S3 } from './hardware.js';
export class SdkconfigGenerator {
  static build(s) {
    const lines = [];
    const set   = (k, v) => lines.push(`${k}=${v}`);
    const en    = (k)    => lines.push(`${k}=y`);
    const dis   = (k)    => lines.push(`# ${k} is not set`);
    const setStr = (k, v) => lines.push(`${k}="${String(v ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`);
    
    const choice = (selected, allOptions) => {
      for (const opt of allOptions) {
        const key = `CONFIG_${opt}`;
        if (opt === selected) en(key); else dis(key);
      }
    };
    lines.push('# Generated by Xiaozhi Web Configurator');
    lines.push('# Equivalent to idf.py menuconfig output');
    lines.push('');
    
    lines.push('# Board & Target');
    set('CONFIG_IDF_TARGET', '"esp32s3"');
    en('CONFIG_BOARD_TYPE_ESP32_S3_N16R8_CUSTOM');
    lines.push('');
    
    lines.push('# ESP-IDF 6.1 System Settings');
    
    choice(`LOG_DEFAULT_LEVEL_${s.build.log_level}`, ['LOG_DEFAULT_LEVEL_NONE','LOG_DEFAULT_LEVEL_ERROR','LOG_DEFAULT_LEVEL_WARN','LOG_DEFAULT_LEVEL_INFO','LOG_DEFAULT_LEVEL_DEBUG','LOG_DEFAULT_LEVEL_VERBOSE']);
    set('CONFIG_ESP_CONSOLE_UART_BAUDRATE', s.build.baud_rate);
    set('CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE', '10096');
    set('CONFIG_ESP_MAIN_TASK_STACK_SIZE', '6584');
    if (s.build.touch_suppress) en('CONFIG_TOUCH_SUPPRESS_DEPRECATE_WARN'); else dis('CONFIG_TOUCH_SUPPRESS_DEPRECATE_WARN');
    if (s.build.md5_partition) en('CONFIG_PARTITION_TABLE_MD5'); else dis('CONFIG_PARTITION_TABLE_MD5');
    lines.push('');
    
    lines.push('# Partition table');
    en('CONFIG_PARTITION_TABLE_CUSTOM');
    set('CONFIG_PARTITION_TABLE_CUSTOM_FILENAME', `"${s.system.partition_table}"`);
    set('CONFIG_PARTITION_TABLE_FILENAME', `"${s.system.partition_table}"`);
    set('CONFIG_PARTITION_TABLE_OFFSET', '0x8000');
    lines.push('');
    
    lines.push('# Flash & PSRAM');
    choice(`ESPTOOLPY_FLASHSIZE_${s.system.flash_size}`, ['ESPTOOLPY_FLASHSIZE_4MB','ESPTOOLPY_FLASHSIZE_8MB','ESPTOOLPY_FLASHSIZE_16MB','ESPTOOLPY_FLASHSIZE_32MB']);
    choice(`ESPTOOLPY_FLASHMODE_${s.system.flash_mode}`,
           ['ESPTOOLPY_FLASHMODE_QIO','ESPTOOLPY_FLASHMODE_QOUT','ESPTOOLPY_FLASHMODE_DIO','ESPTOOLPY_FLASHMODE_DOUT']);
    choice(`ESPTOOLPY_FLASHFREQ_${s.system.flash_freq}`,
           ['ESPTOOLPY_FLASHFREQ_80M','ESPTOOLPY_FLASHFREQ_40M']);
    if (s.system.spiram) {
      en('CONFIG_SPIRAM');
      const psramMode = (s.system.spiram_mode === 'OCT') ? 'OCT' : 'QUAD'; 
      choice(`SPIRAM_MODE_${psramMode}`, ['SPIRAM_MODE_OCT','SPIRAM_MODE_QUAD']);
      choice(`SPIRAM_SPEED_${s.system.spiram_speed}`,
             ['SPIRAM_SPEED_120M','SPIRAM_SPEED_80M','SPIRAM_SPEED_40M']);
      if (s.system.spiram_speed === '120M') en('CONFIG_IDF_EXPERIMENTAL_FEATURES');
    } else {
      dis('CONFIG_SPIRAM');
    }
    lines.push('');
    
    lines.push('# CPU & Cache');
    choice(`ESP_DEFAULT_CPU_FREQ_MHZ_${s.system.cpu_freq}`,
           ['ESP_DEFAULT_CPU_FREQ_MHZ_240','ESP_DEFAULT_CPU_FREQ_MHZ_160']);
    en('CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB');
    en('CONFIG_ESP32S3_DATA_CACHE_32KB');
    en('CONFIG_ESP32S3_DATA_CACHE_LINE_64B');
    lines.push('');
    
    lines.push('# Language');
    const LANGS = ['LANGUAGE_ZH_CN','LANGUAGE_ZH_TW','LANGUAGE_EN_US',
      'LANGUAGE_JA_JP','LANGUAGE_KO_KR','LANGUAGE_VI_VN','LANGUAGE_TH_TH',
      'LANGUAGE_DE_DE','LANGUAGE_FR_FR','LANGUAGE_ES_ES','LANGUAGE_IT_IT',
      'LANGUAGE_RU_RU','LANGUAGE_AR_SA','LANGUAGE_HI_IN','LANGUAGE_MR_IN',
      'LANGUAGE_PT_PT','LANGUAGE_PT_BR','LANGUAGE_PL_PL','LANGUAGE_CS_CZ',
      'LANGUAGE_FI_FI','LANGUAGE_TR_TR','LANGUAGE_ID_ID','LANGUAGE_UK_UA',
      'LANGUAGE_RO_RO','LANGUAGE_BG_BG','LANGUAGE_CA_ES','LANGUAGE_DA_DK',
      'LANGUAGE_EL_GR','LANGUAGE_FA_IR','LANGUAGE_FIL_PH','LANGUAGE_HE_IL',
      'LANGUAGE_HR_HR','LANGUAGE_HU_HU','LANGUAGE_MS_MY','LANGUAGE_NB_NO',
      'LANGUAGE_NL_NL','LANGUAGE_SK_SK','LANGUAGE_SL_SI','LANGUAGE_SV_SE',
      'LANGUAGE_SR_RS'];
    choice(s.general.language, LANGS);
    if (s.general.ota_url)
      set('CONFIG_OTA_URL', `"${s.general.ota_url}"`);
    lines.push('');
    
    lines.push('# Flash Assets');
    choice(s.general.flash_assets,
           ['FLASH_DEFAULT_ASSETS','FLASH_CUSTOM_ASSETS',
            'FLASH_EXPRESSION_ASSETS','FLASH_NONE_ASSETS']);
    if (s.general.flash_assets === 'FLASH_CUSTOM_ASSETS')
      set('CONFIG_CUSTOM_ASSETS_FILE', `"${s.general.custom_assets_file}"`);
    lines.push('');
    
    lines.push('# Display Style');
    choice(s.general.display_style,
           ['USE_DEFAULT_MESSAGE_STYLE','USE_WECHAT_MESSAGE_STYLE',
            'USE_EMOTE_MESSAGE_STYLE']);
    
    if (s.general.display_style === 'USE_DEFAULT_MESSAGE_STYLE' && s.general.multiline_chat) {
      en('CONFIG_USE_MULTILINE_CHAT_MESSAGE');
    } else {
      dis('CONFIG_USE_MULTILINE_CHAT_MESSAGE');
    }
    lines.push('');
    
    lines.push('# Display');
    if (s.display.enable) {
      en('CONFIG_ENABLE_CUSTOM_DISPLAY');
      const DTYPES = ['CUSTOM_DISPLAY_ST7789','CUSTOM_DISPLAY_ST7796',
        'CUSTOM_DISPLAY_ST7735','CUSTOM_DISPLAY_ST7701','CUSTOM_DISPLAY_ILI9341',
        'CUSTOM_DISPLAY_ILI9486','CUSTOM_DISPLAY_GC9A01','CUSTOM_DISPLAY_GC9107',
        'CUSTOM_DISPLAY_NV3023','CUSTOM_DISPLAY_JD9853','CUSTOM_DISPLAY_OLED_SSD1306',
        'CUSTOM_DISPLAY_OLED_SH1106','CUSTOM_DISPLAY_QSPI_AMOLED',
        'CUSTOM_DISPLAY_EPAPER_SSD1681','CUSTOM_DISPLAY_UART',
        'CUSTOM_DISPLAY_USER_CUSTOM','CUSTOM_DISPLAY_NONE'];
      choice(s.display.type, DTYPES);
      set('CONFIG_CUSTOM_DISPLAY_WIDTH',  s.display.width);
      set('CONFIG_CUSTOM_DISPLAY_HEIGHT', s.display.height);
      const isSpi = ['CUSTOM_DISPLAY_ST7789','CUSTOM_DISPLAY_ST7796',
        'CUSTOM_DISPLAY_ST7735','CUSTOM_DISPLAY_ILI9341','CUSTOM_DISPLAY_ILI9486',
        'CUSTOM_DISPLAY_GC9A01','CUSTOM_DISPLAY_GC9107','CUSTOM_DISPLAY_NV3023',
        'CUSTOM_DISPLAY_JD9853','CUSTOM_DISPLAY_ST7701'].includes(s.display.type);
      const isOled = ['CUSTOM_DISPLAY_OLED_SSD1306',
                      'CUSTOM_DISPLAY_OLED_SH1106'].includes(s.display.type);
      const isQspi = s.display.type === 'CUSTOM_DISPLAY_QSPI_AMOLED';
      const isEpaper = s.display.type === 'CUSTOM_DISPLAY_EPAPER_SSD1681';
      const isRgb = s.display.type === 'CUSTOM_DISPLAY_ST7701';
      if (isSpi) {
        set('CONFIG_CUSTOM_DISPLAY_PIN_MOSI', s.display.pin_mosi);
        set('CONFIG_CUSTOM_DISPLAY_PIN_CLK',  s.display.pin_clk);
      }
      set('CONFIG_CUSTOM_DISPLAY_PIN_CS', s.display.pin_cs);
      set('CONFIG_CUSTOM_DISPLAY_PIN_DC', s.display.pin_dc);
      if (s.display.use_rst) {
        en('CONFIG_CUSTOM_DISPLAY_USE_RST');
        set('CONFIG_CUSTOM_DISPLAY_PIN_RST', s.display.pin_rst);
      } else dis('CONFIG_CUSTOM_DISPLAY_USE_RST');
      if (s.display.use_blk) {
        en('CONFIG_CUSTOM_DISPLAY_USE_BLK');
        set('CONFIG_CUSTOM_DISPLAY_PIN_BLK', s.display.pin_blk);
      } else dis('CONFIG_CUSTOM_DISPLAY_USE_BLK');
      if (isOled) {
        set('CONFIG_CUSTOM_DISPLAY_PIN_I2C_SDA', s.display.pin_i2c_sda);
        set('CONFIG_CUSTOM_DISPLAY_PIN_I2C_SCL', s.display.pin_i2c_scl);
      }
      set('CONFIG_CUSTOM_DISPLAY_OFFSET_X', s.display.offset_x);
      set('CONFIG_CUSTOM_DISPLAY_OFFSET_Y', s.display.offset_y);
      if (s.display.mirror_x) en('CONFIG_CUSTOM_DISPLAY_MIRROR_X');
      else dis('CONFIG_CUSTOM_DISPLAY_MIRROR_X');
      if (s.display.mirror_y) en('CONFIG_CUSTOM_DISPLAY_MIRROR_Y');
      else dis('CONFIG_CUSTOM_DISPLAY_MIRROR_Y');
      if (s.display.swap_xy)  en('CONFIG_CUSTOM_DISPLAY_SWAP_XY');
      else dis('CONFIG_CUSTOM_DISPLAY_SWAP_XY');
      if (s.display.invert_color) en('CONFIG_CUSTOM_DISPLAY_INVERT_COLOR');
      else dis('CONFIG_CUSTOM_DISPLAY_INVERT_COLOR');
      if (isQspi) {
        choice(s.display.amoled_chip,
               ['CUSTOM_DISPLAY_AMOLED_SH8601','CUSTOM_DISPLAY_AMOLED_CO5300',
                'CUSTOM_DISPLAY_AMOLED_SPD2010']);
        set('CONFIG_CUSTOM_DISPLAY_QSPI_CS',  s.display.qspi_cs);
        set('CONFIG_CUSTOM_DISPLAY_QSPI_CLK', s.display.qspi_clk);
        for (let n=0;n<=3;n++)
          set(`CONFIG_CUSTOM_DISPLAY_QSPI_D${n}`, s.display[`qspi_d${n}`]);
        set('CONFIG_CUSTOM_DISPLAY_QSPI_RST', s.display.qspi_rst);
      }
      if (isEpaper) set('CONFIG_CUSTOM_DISPLAY_EPAPER_PIN_BUSY', s.display.epaper_busy);
      if (isRgb) {
        set('CONFIG_CUSTOM_DISPLAY_RGB_PCLK',  s.display.rgb_pclk);
        set('CONFIG_CUSTOM_DISPLAY_RGB_DE',    s.display.rgb_de);
        set('CONFIG_CUSTOM_DISPLAY_RGB_VSYNC', s.display.rgb_vsync);
        set('CONFIG_CUSTOM_DISPLAY_RGB_HSYNC', s.display.rgb_hsync);
        for (let n=0;n<=15;n++)
          set(`CONFIG_CUSTOM_DISPLAY_RGB_D${n}`, s.display[`rgb_d${n}`]);
      }
      
      const showUart = s.display.uart_secondary ||
                       s.display.type === 'CUSTOM_DISPLAY_UART';
      if (s.display.uart_secondary) en('CONFIG_ENABLE_CUSTOM_SECONDARY_UART_DISPLAY');
      else dis('CONFIG_ENABLE_CUSTOM_SECONDARY_UART_DISPLAY');
      if (showUart) {
        set('CONFIG_CUSTOM_DISPLAY_UART_PORT',    s.display.uart_port);
        set('CONFIG_CUSTOM_DISPLAY_UART_TX_PIN',  s.display.uart_tx);
        set('CONFIG_CUSTOM_DISPLAY_UART_RX_PIN',  s.display.uart_rx);
        const baudChoices = ['9600','19200','38400','57600','115200','230400','460800','921600'];
        const curBaud = String(s.display.uart_baud || 115200);
        const matchedBaud = baudChoices.includes(curBaud) ? curBaud : '115200';
        choice(`CUSTOM_DISPLAY_UART_BAUDRATE_${matchedBaud}`,
               baudChoices.map(b => `CUSTOM_DISPLAY_UART_BAUDRATE_${b}`));
        set('CONFIG_CUSTOM_DISPLAY_UART_BAUDRATE', matchedBaud);
        choice(s.display.uart_proto,
               ['CUSTOM_DISPLAY_UART_PROTO_NEXTION','CUSTOM_DISPLAY_UART_PROTO_JSON',
                'CUSTOM_DISPLAY_UART_PROTO_RAW_TEXT','CUSTOM_DISPLAY_UART_PROTO_DWIN']);
      }
    } else {
      dis('CONFIG_ENABLE_CUSTOM_DISPLAY');
      dis('CONFIG_ENABLE_CUSTOM_SECONDARY_UART_DISPLAY');
    }
    lines.push('');
    
    lines.push('# Touch');
    if (s.touch.enable) {
      en('CONFIG_ENABLE_CUSTOM_TOUCH');
      choice(s.touch.type,
             ['CUSTOM_TOUCH_CST816S','CUSTOM_TOUCH_GT911','CUSTOM_TOUCH_FT5X06',
              'CUSTOM_TOUCH_USER_CUSTOM','CUSTOM_TOUCH_NONE']);
      set('CONFIG_CUSTOM_TOUCH_PIN_SDA', s.touch.pin_sda);
      set('CONFIG_CUSTOM_TOUCH_PIN_SCL', s.touch.pin_scl);
      set('CONFIG_CUSTOM_TOUCH_PIN_INT', s.touch.pin_int);
      set('CONFIG_CUSTOM_TOUCH_PIN_RST', s.touch.pin_rst);
    } else {
      dis('CONFIG_ENABLE_CUSTOM_TOUCH');
    }
    lines.push('');
    
    lines.push('# Speaker');
    if (s.speaker.enable) {
      en('CONFIG_ENABLE_CUSTOM_SPEAKER');
      const STYPES = ['CUSTOM_AUDIO_DAC_MAX98357A','CUSTOM_AUDIO_DAC_MAX98360A',
        'CUSTOM_AUDIO_DAC_PCM5102A','CUSTOM_AUDIO_SPK_CODEC_ES8311',
        'CUSTOM_AUDIO_SPK_CODEC_ES8388','CUSTOM_AUDIO_SPK_CODEC_ES8374',
        'CUSTOM_AUDIO_SPK_CODEC_ES8389','CUSTOM_AUDIO_SPK_CODEC_BOX',
        'CUSTOM_AUDIO_SPK_CODEC_USER_CUSTOM'];
      choice(s.speaker.type, STYPES);
      set('CONFIG_CUSTOM_AUDIO_SPK_GPIO_DOUT', s.speaker.pin_dout);
      set('CONFIG_CUSTOM_AUDIO_SPK_GPIO_BCLK', s.speaker.pin_bclk);
      set('CONFIG_CUSTOM_AUDIO_SPK_GPIO_LRCK', s.speaker.pin_lrck);
      const isCodecSpk = s.speaker.type.includes('CODEC');
      if (isCodecSpk) {
        set('CONFIG_CUSTOM_AUDIO_SPK_CODEC_I2C_SDA', s.speaker.codec_sda);
        set('CONFIG_CUSTOM_AUDIO_SPK_CODEC_I2C_SCL', s.speaker.codec_scl);
      }
    } else {
      dis('CONFIG_ENABLE_CUSTOM_SPEAKER');
    }
    lines.push('');
    
    lines.push('# Microphone');
    if (s.mic.enable) {
      en('CONFIG_ENABLE_CUSTOM_MIC');
      const MTYPES = ['CUSTOM_AUDIO_MIC_INMP441','CUSTOM_AUDIO_MIC_PDM',
        'CUSTOM_AUDIO_MIC_CODEC_ES8311','CUSTOM_AUDIO_MIC_CODEC_ES8388',
        'CUSTOM_AUDIO_MIC_CODEC_ES8374','CUSTOM_AUDIO_MIC_CODEC_ES8389',
        'CUSTOM_AUDIO_MIC_CODEC_BOX','CUSTOM_AUDIO_MIC_CODEC_USER_CUSTOM'];
      choice(s.mic.type, MTYPES);
      set('CONFIG_CUSTOM_AUDIO_MIC_GPIO_DIN', s.mic.pin_din);
      set('CONFIG_CUSTOM_AUDIO_MIC_GPIO_SCK', s.mic.pin_sck);
      set('CONFIG_CUSTOM_AUDIO_MIC_GPIO_WS',  s.mic.pin_ws);
      const isCodecMic = s.mic.type.includes('CODEC');
      if (isCodecMic) {
        set('CONFIG_CUSTOM_AUDIO_MIC_CODEC_I2C_SDA', s.mic.codec_sda);
        set('CONFIG_CUSTOM_AUDIO_MIC_CODEC_I2C_SCL', s.mic.codec_scl);
      }
    } else {
      dis('CONFIG_ENABLE_CUSTOM_MIC');
    }
    lines.push('');
    
    lines.push('# I2S mode');
    choice(s.audio.i2s_mode,
           ['CUSTOM_AUDIO_I2S_SIMPLEX','CUSTOM_AUDIO_I2S_DUPLEX']);
    lines.push('');
    
    lines.push('# Wake Word & Audio Processing');
    choice(s.wakeword.type,
           ['USE_AFE_WAKE_WORD','USE_ESP_WAKE_WORD',
            'USE_CUSTOM_WAKE_WORD','WAKE_WORD_DISABLED']);
    if (s.wakeword.type === 'USE_CUSTOM_WAKE_WORD') {
      set('CONFIG_CUSTOM_WAKE_WORD',         `"${s.wakeword.custom_word}"`);
      set('CONFIG_CUSTOM_WAKE_WORD_DISPLAY', `"${s.wakeword.custom_display}"`);
      set('CONFIG_CUSTOM_WAKE_WORD_THRESHOLD', s.wakeword.threshold);
    }
    
    const hasAfe = s.wakeword.type === 'USE_AFE_WAKE_WORD' || s.wakeword.device_aec || s.wakeword.server_aec;
    if (s.system.spiram && hasAfe) {
      en('CONFIG_USE_AUDIO_PROCESSOR');
      if (s.wakeword.device_aec) en('CONFIG_USE_DEVICE_AEC');
      else dis('CONFIG_USE_DEVICE_AEC');
      if (s.wakeword.server_aec) en('CONFIG_USE_SERVER_AEC');
      else dis('CONFIG_USE_SERVER_AEC');
    } else {
      dis('CONFIG_USE_AUDIO_PROCESSOR');
      dis('CONFIG_USE_DEVICE_AEC');
      dis('CONFIG_USE_SERVER_AEC');
    }
    if (s.wakeword.send_data) en('CONFIG_SEND_WAKE_WORD_DATA');
    else dis('CONFIG_SEND_WAKE_WORD_DATA');
    
    const canListen = ['USE_AFE_WAKE_WORD', 'USE_CUSTOM_WAKE_WORD'].includes(s.wakeword.type);
    if (canListen && s.wakeword.detection_in_listening) {
      en('CONFIG_WAKE_WORD_DETECTION_IN_LISTENING');
    } else {
      dis('CONFIG_WAKE_WORD_DETECTION_IN_LISTENING');
    }
    lines.push('');
    
    lines.push('# Network & Communication');
    
    const wifiMethod = (s.wifi && s.wifi.method) || s.network.wifi_method;
    choice(wifiMethod,
           ['USE_HOTSPOT_WIFI_PROVISIONING','USE_ESP_BLUFI_WIFI_PROVISIONING']);
    if (wifiMethod === 'USE_ESP_BLUFI_WIFI_PROVISIONING') {
      en('CONFIG_BT_ENABLED');
      en('CONFIG_BT_BLE_42_FEATURES_SUPPORTED');
      en('CONFIG_BT_BLE_BLUFI_ENABLE');
    } else {
      dis('CONFIG_BT_ENABLED');
      dis('CONFIG_BT_BLE_42_FEATURES_SUPPORTED');
      dis('CONFIG_BT_BLE_BLUFI_ENABLE');
    }
    
    
    if (s.uart && s.uart.enable) {
      en('CONFIG_ENABLE_CUSTOM_UART');
      const portSel = s.uart.port === 'CUSTOM_UART_PORT_2' ? 'CUSTOM_UART_PORT_2' : 'CUSTOM_UART_PORT_1';
      choice(portSel, ['CUSTOM_UART_PORT_1', 'CUSTOM_UART_PORT_2']);
      set('CONFIG_CUSTOM_UART_PIN_TX', s.uart.pin_tx);
      set('CONFIG_CUSTOM_UART_PIN_RX', s.uart.pin_rx);
      set('CONFIG_CUSTOM_UART_BAUDRATE', s.uart.baudrate);
      if (s.uart.flow_ctrl) {
        en('CONFIG_CUSTOM_UART_USE_FLOW_CONTROL');
        set('CONFIG_CUSTOM_UART_PIN_RTS', s.uart.pin_rts);
        set('CONFIG_CUSTOM_UART_PIN_CTS', s.uart.pin_cts);
      } else dis('CONFIG_CUSTOM_UART_USE_FLOW_CONTROL');
    } else {
      dis('CONFIG_ENABLE_CUSTOM_UART');
    }
    
    if (s.mcp ? s.mcp.enable : s.network.mcp_enable) {
      en('CONFIG_ENABLE_CUSTOM_MCP_SERVER');
    } else {
      dis('CONFIG_ENABLE_CUSTOM_MCP_SERVER');
    }
    lines.push('');

    lines.push('# Buttons & Input');
    if (s.buttons.boot_enable) {
      en('CONFIG_CUSTOM_ENABLE_BUTTON_BOOT');
      set('CONFIG_CUSTOM_BUTTON_BOOT_GPIO', s.buttons.boot_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_BUTTON_BOOT');
    if (s.buttons.touch_enable) {
      en('CONFIG_CUSTOM_ENABLE_BUTTON_TOUCH');
      set('CONFIG_CUSTOM_BUTTON_TOUCH_GPIO', s.buttons.touch_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_BUTTON_TOUCH');
    if (s.buttons.vol_enable) {
      en('CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME');
      set('CONFIG_CUSTOM_BUTTON_VOL_UP_GPIO',   s.buttons.vol_up_gpio);
      set('CONFIG_CUSTOM_BUTTON_VOL_DOWN_GPIO',  s.buttons.vol_down_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_BUTTON_VOLUME');
    if (s.buttons.slider_enable) {
      en('CONFIG_CUSTOM_ENABLE_TOUCH_SLIDER');
      set('CONFIG_CUSTOM_TOUCH_SLIDER_PAD1_GPIO', s.buttons.slider_pad1);
      set('CONFIG_CUSTOM_TOUCH_SLIDER_PAD2_GPIO', s.buttons.slider_pad2);
      set('CONFIG_CUSTOM_TOUCH_SLIDER_PAD3_GPIO', s.buttons.slider_pad3);
    } else dis('CONFIG_CUSTOM_ENABLE_TOUCH_SLIDER');
    if (s.buttons.rotary_enable) {
      en('CONFIG_CUSTOM_ENABLE_PERIPH_ROTARY_ENCODER');
      set('CONFIG_CUSTOM_PERIPH_ENCODER_PHASE_A', s.buttons.rotary_a);
      set('CONFIG_CUSTOM_PERIPH_ENCODER_PHASE_B', s.buttons.rotary_b);
      set('CONFIG_CUSTOM_PERIPH_ENCODER_KEY_PIN', s.buttons.rotary_key);
    } else dis('CONFIG_CUSTOM_ENABLE_PERIPH_ROTARY_ENCODER');
    if (s.buttons.user_custom_sensors) en('CONFIG_CUSTOM_ENABLE_USER_CUSTOM_SENSORS');
    else dis('CONFIG_CUSTOM_ENABLE_USER_CUSTOM_SENSORS');
    lines.push('');
    
    lines.push('# Camera');
    if (s.camera.enable) {
      en('CONFIG_ENABLE_CUSTOM_CAMERA');
      choice(s.camera.sensor,
             ['CUSTOM_CAMERA_OV2640','CUSTOM_CAMERA_OV3660','CUSTOM_CAMERA_OV5640',
              'CUSTOM_CAMERA_SC030IOT','CUSTOM_CAMERA_USB_UVC','CUSTOM_CAMERA_USER_CUSTOM']);
      if (s.camera.sensor !== 'CUSTOM_CAMERA_USB_UVC') {
        set('CONFIG_CUSTOM_CAM_PIN_XCLK',  s.camera.pin_xclk);
        set('CONFIG_CUSTOM_CAM_PIN_PCLK',  s.camera.pin_pclk);
        set('CONFIG_CUSTOM_CAM_PIN_VSYNC', s.camera.pin_vsync);
        set('CONFIG_CUSTOM_CAM_PIN_HREF',  s.camera.pin_href);
        set('CONFIG_CUSTOM_CAM_PIN_SIOD',  s.camera.pin_siod);
        set('CONFIG_CUSTOM_CAM_PIN_SIOC',  s.camera.pin_sioc);
        if (s.camera.use_reset) {
          en('CONFIG_CUSTOM_CAM_USE_RESET');
          set('CONFIG_CUSTOM_CAM_PIN_RESET', s.camera.pin_reset);
        } else dis('CONFIG_CUSTOM_CAM_USE_RESET');
        if (s.camera.use_pwdn) {
          en('CONFIG_CUSTOM_CAM_USE_PWDN');
          set('CONFIG_CUSTOM_CAM_PIN_PWDN', s.camera.pin_pwdn);
        } else dis('CONFIG_CUSTOM_CAM_USE_PWDN');
        for (let n=0;n<=7;n++)
          set(`CONFIG_CUSTOM_CAM_PIN_D${n}`, s.camera[`pin_d${n}`]);
        if (s.camera.hmirror) en('CONFIG_CUSTOM_CAM_HMIRROR');
        else dis('CONFIG_CUSTOM_CAM_HMIRROR');
        if (s.camera.vflip) en('CONFIG_CUSTOM_CAM_VFLIP');
        else dis('CONFIG_CUSTOM_CAM_VFLIP');
      }
    } else dis('CONFIG_ENABLE_CUSTOM_CAMERA');
    lines.push('');
    
    lines.push('# LED');
    if (s.led.enable) {
      en('CONFIG_ENABLE_CUSTOM_LEDS');
      choice(s.led.type,
             ['CUSTOM_LED_WS2812','CUSTOM_LED_SINGLE_PWM',
              'CUSTOM_LED_CIRCULAR_STRIP','CUSTOM_LED_USER_CUSTOM','CUSTOM_LED_NONE']);
      set('CONFIG_CUSTOM_LED_GPIO',  s.led.gpio);
      set('CONFIG_CUSTOM_LED_COUNT', s.led.count);
      if (['CUSTOM_LED_WS2812','CUSTOM_LED_CIRCULAR_STRIP'].includes(s.led.type)) {
        if (s.led.rainbow) en('CONFIG_CUSTOM_LED_FAST_RAINBOW_EFFECT');
        else dis('CONFIG_CUSTOM_LED_FAST_RAINBOW_EFFECT');
      }
    } else dis('CONFIG_ENABLE_CUSTOM_LEDS');
    lines.push('');
    
    lines.push('# Actuators (Servo / Buzzer / Haptic)');
    
    if (s.mcp && s.mcp.lamp) {
      en('CONFIG_CUSTOM_MCP_TOOL_LAMP');
      set('CONFIG_CUSTOM_MCP_TOOL_LAMP_GPIO', s.mcp.lamp_gpio);
    } else {
      dis('CONFIG_CUSTOM_MCP_TOOL_LAMP');
    }
    if (s.actuators.servo_enable) {
      en('CONFIG_CUSTOM_ENABLE_SERVO_DOG');
      set('CONFIG_CUSTOM_SERVO_DOG_PWM_GPIO', s.actuators.servo_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SERVO_DOG');
    if (s.actuators.buzzer_enable) {
      en('CONFIG_ENABLE_BUZZER');
      set('CONFIG_BUZZER_PIN', s.actuators.buzzer_gpio);
    } else dis('CONFIG_ENABLE_BUZZER');
    if (s.actuators.haptic_enable) {
      en('CONFIG_ENABLE_HAPTIC_MOTOR');
      set('CONFIG_HAPTIC_PIN', s.actuators.haptic_gpio);
    } else dis('CONFIG_ENABLE_HAPTIC_MOTOR');
    lines.push('');
    
    lines.push('# Motor & Relay');
    if (s.motor.relay_enable) {
      en('CONFIG_CUSTOM_PERIPH_RELAY_ENABLE');
      set('CONFIG_CUSTOM_PERIPH_RELAY_GPIO', s.motor.relay_gpio);
    } else dis('CONFIG_CUSTOM_PERIPH_RELAY_ENABLE');
    if (s.motor.dc_enable) {
      en('CONFIG_CUSTOM_ENABLE_PERIPH_MOTOR_DC_HBRIDGE');
      choice(s.motor.dc_driver,
             ['CUSTOM_MOTOR_DRIVER_TB6612','CUSTOM_MOTOR_DRIVER_L9110S',
              'CUSTOM_MOTOR_DRIVER_DRV8833']);
      set('CONFIG_CUSTOM_PERIPH_MOTOR_PWMA_PIN', s.motor.pwma);
      set('CONFIG_CUSTOM_PERIPH_MOTOR_DIRA_PIN', s.motor.dira);
      set('CONFIG_CUSTOM_PERIPH_MOTOR_PWMB_PIN', s.motor.pwmb);
      set('CONFIG_CUSTOM_PERIPH_MOTOR_DIRB_PIN', s.motor.dirb);
    } else dis('CONFIG_CUSTOM_ENABLE_PERIPH_MOTOR_DC_HBRIDGE');
    lines.push('');
    
    lines.push('# Sensors');
    if (s.sensors.dht_enable) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_DHT11_22');
      set('CONFIG_CUSTOM_SENSOR_DHT_GPIO', s.sensors.dht_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_DHT11_22');
    if (s.sensors.temp_enable) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_I2C_TEMP_HUMID');
      if (s.sensors.aht20) en('CONFIG_CUSTOM_ENABLE_SENSOR_AHT20');
      else dis('CONFIG_CUSTOM_ENABLE_SENSOR_AHT20');
      set('CONFIG_CUSTOM_SENSOR_I2C_SDA', s.sensors.temp_sda);
      set('CONFIG_CUSTOM_SENSOR_I2C_SCL', s.sensors.temp_scl);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_I2C_TEMP_HUMID');
    if (s.sensors.bmp280) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_BMP280');
      set('CONFIG_CUSTOM_SENSOR_BMP280_I2C_SDA', s.sensors.bmp280_sda);
      set('CONFIG_CUSTOM_SENSOR_BMP280_I2C_SCL', s.sensors.bmp280_scl);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_BMP280');
    if (s.sensors.bh1750) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_BH1750');
      set('CONFIG_CUSTOM_SENSOR_BH1750_I2C_SDA', s.sensors.bh1750_sda);
      set('CONFIG_CUSTOM_SENSOR_BH1750_I2C_SCL', s.sensors.bh1750_scl);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_BH1750');
    if (s.sensors.ldr) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_LDR');
      set('CONFIG_CUSTOM_SENSOR_LDR_ADC_CHANNEL', s.sensors.ldr_ch);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_LDR');
    if (s.sensors.gas_co2) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_GAS_CO2');
      if (s.sensors.gas_scd4x) en('CONFIG_CUSTOM_SENSOR_GAS_SCD4X');
      else dis('CONFIG_CUSTOM_SENSOR_GAS_SCD4X');
      set('CONFIG_CUSTOM_SENSOR_GAS_I2C_SDA', s.sensors.gas_sda);
      set('CONFIG_CUSTOM_SENSOR_GAS_I2C_SCL', s.sensors.gas_scl);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_GAS_CO2');
    if (s.sensors.gas_mq) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_GAS_ANALOG_MQ');
      set('CONFIG_CUSTOM_SENSOR_MQ_ANALOG_PIN', s.sensors.gas_mq_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_GAS_ANALOG_MQ');
    if (s.sensors.hcsr04) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_HCSR04');
      set('CONFIG_CUSTOM_SENSOR_HCSR04_TRIG_GPIO', s.sensors.hcsr04_trig);
      set('CONFIG_CUSTOM_SENSOR_HCSR04_ECHO_GPIO', s.sensors.hcsr04_echo);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_HCSR04');
    if (s.sensors.pir) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_PIR');
      set('CONFIG_CUSTOM_SENSOR_PIR_GPIO', s.sensors.pir_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_PIR');
    if (s.sensors.vibration) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_VIBRATION_SW420');
      set('CONFIG_CUSTOM_SENSOR_VIBRATION_PIN', s.sensors.vibration_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_VIBRATION_SW420');
    if (s.sensors.flame) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_FLAME');
      set('CONFIG_CUSTOM_SENSOR_FLAME_PIN', s.sensors.flame_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_FLAME');
    en('CONFIG_ENABLE_CUSTOM_SENSORS');  
    lines.push('');
    
    lines.push('# Power & Battery');
    if (s.power.battery_enable) {
      en('CONFIG_CUSTOM_ENABLE_BATTERY_MONITOR');
      if (s.power.battery_adc) {
        en('CONFIG_CUSTOM_BATTERY_MONITOR_ADC');
        set('CONFIG_CUSTOM_BATTERY_ADC_CHANNEL', s.power.battery_ch);
        set('CONFIG_CUSTOM_BATTERY_DIVIDER_R1',  s.power.battery_r1);
        set('CONFIG_CUSTOM_BATTERY_DIVIDER_R2',  s.power.battery_r2);
      } else dis('CONFIG_CUSTOM_BATTERY_MONITOR_ADC');
    } else {
      dis('CONFIG_CUSTOM_ENABLE_BATTERY_MONITOR');
      en('CONFIG_CUSTOM_BATTERY_MONITOR_NONE');
    }
    if (s.power.ina2xx) {
      en('CONFIG_CUSTOM_ENABLE_SENSOR_INA2XX');
      if (s.power.ina219) en('CONFIG_CUSTOM_SENSOR_INA219');
      else dis('CONFIG_CUSTOM_SENSOR_INA219');
      set('CONFIG_CUSTOM_SENSOR_INA2XX_I2C_SDA', s.power.ina_sda);
      set('CONFIG_CUSTOM_SENSOR_INA2XX_I2C_SCL', s.power.ina_scl);
    } else dis('CONFIG_CUSTOM_ENABLE_SENSOR_INA2XX');
    if (s.power.tp4056) {
      en('CONFIG_CUSTOM_ENABLE_PERIPH_BATTERY_CHARGING_DETECT');
      set('CONFIG_CUSTOM_PERIPH_BATTERY_CHRG_PIN', s.power.tp4056_gpio);
    } else dis('CONFIG_CUSTOM_ENABLE_PERIPH_BATTERY_CHARGING_DETECT');
    lines.push('');
    return lines;
  }
}
